weights: yolov5x.pt
cfg: models/yolov5x.yaml
data: data/stairall40sep.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 300
batch_size: 10
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: trained_weights/all40sep
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 20
freeze:
- 0
save_period: 20
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: trained_weights/all40sep/exp2
